apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent
  namespace: fluent
data:
  fluent_conf: |
    @include kubernetes.conf

    
      @type kafka_buffered

      brokers             192.168.1.59:9092

      topic_key             TutorialTopic
      default_topic         TutorialTopic
      output_data_type      json
      output_include_tag    true
      output_include_time   true
      get_kafka_client_log  false

      required_acks         1
      compression_codec     gzip