gitlab_external_url: "http://host.minikube.internal/"
elasticsearch_network_host: 0.0.0.0
kibana_elasticsearch_url: "http://192.168.99.1:9200"
kibana_elasticsearch_username: "elastic"
kibana_elasticsearch_password: "changeme"
