kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: vmartinvega/jenkins:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: CASC_JENKINS_CONFIG
              value: "/var/jenkins_home/jenkins-conf.yaml"
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config-volume
              mountPath: /var/jenkins_home/jenkins-conf.yaml
              subPath: jenkins-conf.yaml
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-storage
        - name: jenkins-config-volume
          configMap:
            name: jenkins-conf
            items:
            - key: jenkins-conf.yaml
              path: jenkins-conf.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32000
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-webservice
spec:
  ports:
    - port: 8081
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-tcp-port
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp-port
spec:
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-webservice
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: jenkins.local.nip.io
    http:
      paths:
      - backend:
          serviceName: jenkins-webservice
          servicePort: 8081
        path: /
